from pydantic_settings import BaseSettings


class RobotConfig(BaseSettings):
    """Robot configuration."""

    joint_names: list[str] = [
        "robot0:WRJ1",
        "robot0:WRJ0",
        "robot0:FFJ3",
        "robot0:FFJ2",
        "robot0:FFJ1",
        "robot0:FFJ0",
        "robot0:MFJ3",
        "robot0:MFJ2",
        "robot0:MFJ1",
        "robot0:MFJ0",
        "robot0:RFJ3",
        "robot0:RFJ2",
        "robot0:RFJ1",
        "robot0:RFJ0",
        "robot0:LFJ4",
        "robot0:LFJ3",
        "robot0:LFJ2",
        "robot0:LFJ1",
        "robot0:LFJ0",
        "robot0:THJ4",
        "robot0:THJ3",
        "robot0:THJ2",
        "robot0:THJ1",
        "robot0:THJ0",
    ]
    joint_qpos_addrs: list[int] = [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
    ]
